# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux-cli" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "845745f92e91b7e243786c94c906871b047170cf0c04b22e952f4a890ef4b9b6"
      url "https://github.com/eyra/flux-cli/releases/download/v#{version}/flux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b2b883fb8b4f45c46fdc7a11607d9407ce0493afc036b8c1ae57b58e0288a766"
      url "https://github.com/eyra/flux-cli/releases/download/v#{version}/flux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e3df9c9f706b9d44edd1c66ea3f34db000afe1c6891019520c347ffd1b723e39"
      url "https://github.com/eyra/flux-cli/releases/download/v#{version}/flux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f33fac9a87ab6b5590cbe94e171cc7494b804dfd95f1de22e599911bdc03ba76"
      url "https://github.com/eyra/flux-cli/releases/download/v#{version}/flux_linux_amd64.tar.gz"
    end
  end

  name "flux-cli"
  desc "Command-line interface for Flux project management"
  homepage "https://github.com/eyra/flux-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flux"]
    end
  end

  # No zap stanza required
end
