# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux-cli" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "5341f2ba85c79b9aad27d44209ced1800bde960ca62643bb1f5e37c6ed3c4e8f"
      url "https://github.com/eyra/flux-cli/releases/download/v#{version}/flux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "87382db0e8b29918c324617874cae30948959a8ff6bd6484c306a40bfdfb978a"
      url "https://github.com/eyra/flux-cli/releases/download/v#{version}/flux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e600537d9b82e74e1cdfc64a7af6209e04fee77ab092272a96cb3c3d384a327c"
      url "https://github.com/eyra/flux-cli/releases/download/v#{version}/flux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5e82c4a85c670cf5e1f2e9a52adcc6c7e85390c019518b128343eba786cb7be0"
      url "https://github.com/eyra/flux-cli/releases/download/v#{version}/flux_linux_amd64.tar.gz"
    end
  end

  name "flux-cli"
  desc "Command-line interface for Flux project management"
  homepage "https://github.com/eyra/flux-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flux"]
    end
  end

  # No zap stanza required
end
