# This file was generated by GoReleaser. DO NOT EDIT.
cask "flux-cli" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "f50a0f1c91eefff2112c19daf431fc6e4db521d657fbacf472fc4eefe1e5e022"
      url "https://github.com/eyra/flux-cli/releases/download/v0.2.1/flux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2664904ada5f8d8ddfca54c0b00f4b1a8b422f5795deea23327d8fa8fc3a0f1"
      url "https://github.com/eyra/flux-cli/releases/download/v0.2.1/flux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8f6c48f68b675f61ccb8907cc0741dd48cf4b1efce8afbb406490d04075ca09b"
      url "https://github.com/eyra/flux-cli/releases/download/v0.2.1/flux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "09da120dc995df7847e6506b51cfca66a90af5a981377298130aa095c51deff8"
      url "https://github.com/eyra/flux-cli/releases/download/v0.2.1/flux_linux_amd64.tar.gz"
    end
  end

  name "flux-cli"
  desc "Command-line interface for Flux project management"
  homepage "https://github.com/eyra/flux-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flux"]
    end
  end

  # No zap stanza required
end
